### ISSUE TITLE
[Meta] Documenting manual deployment

### ISSUE THREAD

**Issue by terion-name** [graphcool/prisma#1808]
I've asked a question about this on forum, but no luck
https://www.graph.cool/forum/t/how-to-run-generators-migrators-manually/2405

Docs say:
> The infrastructure for self-hosted (and local) clusters is entirely based on Docker. In that sense, it’s theoretically possible to deploy your Prisma service simply with the Docker CLI.

But there is no information and it cannot be found, how to run generator and migrator hooks when starting prisma service via docker, not via `prisma deploy`

**Comment by marktani** [comment]
Thanks @terion-name 🙂 There's been a lot of questions about cluster deployment and operating a cluster on Digital Ocean or elsewhere. We improved documentation around this topic [here](https://www.prismagraphql.com/docs/reference/clusters/docker-aira9zama5), [here](https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(docker-machine)-texoo9aemu) and [here](https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(manual)-texoo6aemu), and will continue to do so.

I'm keeping a list of questions here, so we can answer them one by one overtime:

* [ ] https://www.graph.cool/forum/t/how-to-run-generators-migrators-manually/2405?u=nilan
* [ ] https://www.graph.cool/forum/t/upgrading-a-cluster-on-digital-ocean/2378?u=nilan
* [ ] https://www.graph.cool/forum/t/cluster-deployment-fail-to-query-deployed-project-on-remote-self-hosted-cluster/2414?u=nilan
* [ ] https://www.graph.cool/forum/t/how-to-eject-prisma-and-use-docker-compose-yml-to-deploy-prisma-with-other-services-e-g-node-js-server/2392?u=nilan
* [ ] https://www.graph.cool/forum/t/cant-start-prisma-local-cluster-on-virtual-private-server/2149?u=nilan
* [ ] https://www.graph.cool/forum/t/production-ready-prisma-on-aws-eb-ecs-what-are-valid-options/2380?u=nilan
---
* [ ] https://github.com/graphcool/prisma/issues/1779
* [ ] https://github.com/graphcool/prisma/issues/1771

**Comment by terion-name** [comment]
@marktani thank you, but still there is no information about how to run prisma service manually, without `prisma deploy`. It is written how to start it up, but nothing about how to run migrations/seeds/etc
Or it is simply triggered on container start?

**Comment by terion-name** [comment]
Also, here: https://www.prismagraphql.com/docs/reference/clusters/docker-aira9zama5
There is no information about: 
1. how to provide volume with prisma app code (if it is located not in the root)
2. How to link different DB service (if I have something like `musql-cluster` in my infrastructure)

**Comment by marktani** [comment]
Hey @terion-name, is there a reason you don't want to use `prisma deploy` with your own cluster? Because you can do that 🙂

**Comment by terion-name** [comment]
@marktani because I build a highly complex microservice-based application, where Prisma is just a part of it. And I need to have full manual centralized control over infrastructure and microservices.

**Comment by terion-name** [comment]
@marktani in short:
1. Control the entire infrastructure with docker
2. Use scalable mysql cluster as centralized db subsystem
3. Use Prisma only as internal graphql db-abstraction and crud without application (by proxying crud api out), multiple instances of which will be used stitched by apollo server as an aggregated crud for different applications.

I can't accomplish this using `prisma deploy`, I need full manual control for this

**Comment by marktani** [comment]
I moved the list of topics here: https://github.com/graphcool/prisma/issues/2189.

@terion-name closing this, because your discussion progressed in many other issues.
